package cl.pro.music.rest.api.viewmodel.error;

import lombok.NoArgsConstructor;

@NoArgsConstructor
public enum ErrorCodes {

    ERROR_NO_CONTROLADO,
    CASO_BORDE,
    PETICION_MAL_FORMADA,
    NO_ENCONTRADO,
    VALORES_INVALIDOS,
    ERROR_EN_JPA,
    YA_EXISTE,
    TIPO_INCORRECTO,
    ERROR_UPDATE_VALORES_NULOS,
    VIOLACION_DE_RESTRICCIONES,
    RUT_NO_VALIDO,
    ERROR_EN_SERVICIO_EXTERNO,
    ERROR_INSERTAR_REGISTRO,
    NADA_QUE_MOSTRAR,
    ENTIDAD_CONFLICTO,
    EDAD_ADICIONAL_NO_PERMITIDA,
    CONFLICTO_LDAP,
    CONFLICTO_SERVICIO_SOAP,
    CONFLICTO,
    MONTO_VENTA_INFERIOR_AL_PAGADO

}
